#!/usr/bin/env bash

while true; do
    update_count=$(/usr/bin/checkupdates | wc -l)
    
    if [ "$update_count" -gt 0 ]; then
        echo "$update_count new updates" 
        sleep 30 
    else
        echo "No new updates" 
        sleep 600

    fi
done
