import = ["~/.config/alacritty/theme.toml"]

[cursor.style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
family = "JetBrains Mono Nerd Font"
#family = "CaskaydiaCove Nerd Font"
style = "semibold"

[font.bold]
family = "JetBrains Mono Nerd Font"
#family = "CaskaydiaCove Nerd Font"
style = "bold"
    
[font.italic]
family = "JetBrains Mono Nerd Font"
#family = "CaskaydiaCove Nerd Font"
style = "italic"

[window]
opacity = 0.75
